Bunny/Areas/Web/Controllers/CoinController.cs
using System.Runtime.InteropServices.WindowsRuntime;
using System.Threading.Tasks;
using Bunny.Areas.Web.Controllers.BaseController;
using Bunny.Service.Interface.Coin;
using Microsoft.AspNetCore.Mvc;

namespace Bunny.Areas.Web.Controllers
{
    [Route(EndPoint)]
    public class CoinController : BaseWebController
    {
        public const string EndPoint = AreaName + "/coin";
        public const string CoinEndpoint = "index";
        public const string ActiveEndpoint = "active";
        public const string ChangeMinDisableNotificationEndpoint = "change-min-disable";

        private readonly ICoinService _coinService;

        public CoinController(ICoinService coinService)
        {
            _coinService = coinService;
        }

        // GET
        [Route(CoinEndpoint)]
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [Route(ActiveEndpoint)]
        [HttpPost]
        public async Task<JsonResult> Active(int id)
        {
            await _coinService.Active(id).ConfigureAwait(false);
            return Json("success");
        }

        [Route(ChangeMinDisableNotificationEndpoint)]
        [HttpPost]
        public async Task<JsonResult> ChangeMinDisableNotification(int id, int numberChange)
        {
            await _coinService.ChangeMinDisable(id, numberChange).ConfigureAwait(false);
            return Json("success");
        }
    }
}

Bunny/Areas/Web/Controllers/CoinManagerController.cs
using Bunny.Areas.Web.Controllers.BaseController;
using Microsoft.AspNetCore.Mvc;

namespace Bunny.Areas.Web.Controllers
{
    [Route(EndPoint)]
    public class CoinManagerController : BaseWebController
    {
        public const string EndPoint = AreaName + "/coin-manager";
        public const string CoinManagerEndpoint = "index";


        // GET
        [Route(CoinManagerEndpoint)]
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
    }
}

Bunny/Areas/Web/Controllers/UserController.cs
using System.Threading.Tasks;
using Bunny.Areas.Web.Controllers.BaseController;
using Bunny.DataTable;
using Bunny.DataTable.Models.Request;
using Bunny.Extensions;
using Bunny.Middle;
using Bunny.Middle.Auth.Attributes;
using Bunny.Middle.User;
using Bunny.Model.User;
using Bunny.Service.Interface.User;
using Microsoft.AspNetCore.Mvc;

namespace Bunny.Areas.Web.Controllers
{
    [Route(EndPoint)]
    public class UserController : BaseWebController
    {
        public const string EndPoint = AreaName + "/user";
        public const string UserEndpoint = "index";
        public const string ListingEndpoint = "";
        public const string EditEndpoint = "edit";
        public const string SubmitEditEndpoint = "submit-edit";
        public const string AddEndpoint = "add";
        public const string SubmitAddEndpoint = "submit-add";
        public const string RemoveEndpoint = "remove";
        private readonly IUserService _userService;

        public UserController(IUserService userService)
        {
            _userService = userService;
        }
        // GET
        [Route(UserEndpoint)]
        [HttpGet]
        [Auth(Enums.Role.Admin, Enums.Role.Manager)]
        public IActionResult Index()
        {
            return
            View();
        }
        /// <summary>
        ///     Edit 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Route(EditEndpoint)]
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var model = await _userService.GetEdit(id).ConfigureAwait(true);
            return View(model);
        }
        [Route(SubmitEditEndpoint)]
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<JsonResult> SubmitEdit([FromBody]UserEditModel model)
        {
            if (!ModelState.IsValid)
            {
                //this.SetNotify("Edit Fail", "Edit user fail, please try again", NotifyStatus.Error);
                return Json("Fail");
            }

            await _userService.SubmitEdit(model, LoggedInUser.Current.Id, Constants.UserManager.PasswordDefault)
                .ConfigureAwait(false);
            //this.SetNotify("Edit Success", "User has been updated successful", NotifyStatus.Success);
            return Json("Success");
        }

        /// <summary>
        ///     Add 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Route(AddEndpoint)]
        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var model = await _userService.GetAdd().ConfigureAwait(true);
            return View(model);
        }
        [Route(SubmitAddEndpoint)]
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> SubmitAdd([FromForm]UserAddModel model)
        {
            if (!ModelState.IsValid)
            {
                this.SetNotify("Edit Fail", "Edit user fail, please try again", NotifyStatus.Error);
                return RedirectToAction("Add");
            }

            await _userService.SubmitAdd(model, LoggedInUser.Current.Id).ConfigureAwait(false);
            this.SetNotify("Edit Success", "User has been updated successful", NotifyStatus.Success);
            return RedirectToAction("Index");
        }

        [Route(RemoveEndpoint)]
        [HttpPost]
       
        public async Task<JsonResult> Remove(int id)
        {
            await _userService.RemoveAsync(id, LoggedInUser.Current.Id).ConfigureAwait(false);
            return Json(new { });
        }
    }
}

Bunny/Controllers/Components/HeaderViewComponent.cs
using System.Threading.Tasks;
using Bunny.Middle;
using Bunny.Middle.Auth.Filters;
using Bunny.Middle.User;
using Bunny.Model.User;
using Microsoft.AspNetCore.Mvc;

namespace Bunny.Controllers.Components
{
    [ServiceFilter(typeof(LoggedInUserBinderFilter))]
    public class HeaderViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(bool isAdminPortal)
        {
            var loggedInUserModel = LoggedInUser.Current;
            var isManager = loggedInUserModel.RoleId == (int)Enums.Role.Admin || loggedInUserModel.RoleId == (int)Enums.Role.Manager;
            var result = new UserHeaderViewModel
            {
                FirstName = loggedInUserModel?.FirstName,
                LastName = loggedInUserModel?.LastName,
                Id = loggedInUserModel?.Id ?? 0,
                IsAdminPortal = isAdminPortal,
                IsManager = isManager
            };
            return await Task.FromResult<IViewComponentResult>(View("Header", result)).ConfigureAwait(false);
        }
    }
}

Bunny/Views/Shared/_Layout.cshtml
@using Bunny.Web
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>@ViewData["Title"] - Bunny</title>

    <script type="text/javascript" src="~/vendor/breakpoints/breakpoints.min.js"></script>
    <script type="text/javascript">
        Breakpoints();
    </script>


    @{
        await Html.RenderPartialAsync("~/Areas/Web/Views/Shared/Asset/_Style.cshtml").ConfigureAwait(true);
    }
    <link rel="stylesheet" href="~/Assets/Style/Global.css" />
    <!-- JS -->
    <!-- jquery js -->
    @*<script type="text/javascript" src="~/lib/jquery/dist/jquery.js"></script>*@
    @*<script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>*@
    <script type="text/javascript" src="~/vendor/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="~/vendor/jquery-validation/jquery.validate.js"></script>
    <script type="text/javascript" src="~/vendor/jquery-validation/additional-methods.js"></script>
    <script type="text/javascript" src="~/vendor/jquery-validation/jquery.validate.unobtrusive.min.js"></script>
    <script type="text/javascript" src="~/vendor/jquery-validation/jquery.unobtrusive-ajax.min.js"></script>

    <!-- bootstrap js -->
    <script type="text/javascript" src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>

    <!-- datatable js -->
    @*<script type="text/javascript" charset="utf8" src="~/Assets/client-side/plugin/datatables/jquery.dataTables.min.js"></script>*@
    @*<script type="text/javascript" charset="utf8" src="~/Assets/client-side/plugin/datatables/dataTables.responsive.js"></script>
        <script type="text/javascript" src="~/Assets/client-side/plugin/jquery-ui/jquery-ui.js"></script>*@
    <!-- DataTable -->
    <script type="text/javascript" src="~/vendor/datatables.net/jquery.dataTables.js"></script>
    <script type="text/javascript" src="~/vendor/datatables.net-bs4/dataTables.bootstrap4.js"></script>

    <!-- DataTable - Column Filter -->
    <script type="text/javascript" src="~/vendor/datatables-columnfilter/jquery.dataTables.columnFilter.min.js"></script>

    <!-- DataTable - ColVis -->
    <script type="text/javascript" src="~/vendor/datatables-colvis/dataTables.colVis.min.js"></script>

    <!-- DataTable - Other Plugin -->
    <script type="text/javascript" src="~/vendor/datatables.net-fixedheader-bs4/dataTables.fixedHeader.js"></script>
    <script type="text/javascript" src="~/vendor/datatables.net-fixedcolumns-bs4/dataTables.fixedColumns.js"></script>
    <script type="text/javascript" src="~/vendor/datatables.net-rowgroup-bs4/dataTables.rowGroup.js"></script>
    <script type="text/javascript" src="~/vendor/datatables.net-scroller-bs4/dataTables.scroller.js"></script>
    <script type="text/javascript" src="~/vendor/datatables.net-select-bs4/dataTables.select.js"></script>
    <script type="text/javascript" src="~/vendor/datatables.net-responsive/dataTables.responsive.js"></script>
    <script type="text/javascript" src="~/vendor/datatables.net-responsive-bs4/responsive.bootstrap4.js"></script>
    <script type="text/javascript" src="~/vendor/datatables.net-buttons/dataTables.buttons.js"></script>
    <script type="text/javascript" src="~/vendor/datatables.net-buttons/buttons.html5.js"></script>
    <script type="text/javascript" src="~/vendor/datatables.net-buttons/buttons.flash.js"></script>
    <script type="text/javascript" src="~/vendor/datatables.net-buttons/buttons.print.js"></script>
    <script type="text/javascript" src="~/vendor/datatables.net-buttons/buttons.colVis.js"></script>
    <script type="text/javascript" src="~/vendor/datatables.net-buttons-bs4/buttons.bootstrap4.js"></script>
    <script type="text/javascript" src="~/vendor/bootstrap-sweetalert/sweetalert.min.js"></script>

    <!-- global js -->
    <script src="~/Assets/Script/Global/Components/Sidebar.js"></script>
    <script src="~/js/Bunny.js"></script>
</head>
@{
    var controllerName = ViewContext.RouteData.Values["controller"].ToString().ToLower();
    var isAdminPortal = controllerName == "masterpage" || controllerName == "user" || controllerName == "coinmanager" || controllerName == "settingbinance"
                        || controllerName == "coin";
}
<body>
    <div id="page_container">
        <!-- Header -->
        @await Component.InvokeAsync("Header", isAdminPortal)
        <!-- end header -->
        @if (isAdminPortal)
        {
            <div id="wrapper" class="active">

                <!-- Sidebar -->
                <!-- Sidebar -->
                <div id="sidebar-wrapper">
                    <ul id="sidebar_menu" class="sidebar-nav">
                        <li class="sidebar-brand"><a id="menu-toggle" href="#">Menu<span id="main_icon" class="glyphicon glyphicon-align-justify"></span></a></li>
                    </ul>
                    <ul class="sidebar-nav" id="sidebar">
                        <li><a class="side-menu-item-content" href="@Url.Action("Index", "User")">User<span class="sub_icon glyphicon glyphicon-link"></span></a></li>
                        @*<li><a class="side-menu-item-content" href="@Url.Action("Index", "Home")">Home<span class="sub_icon glyphicon glyphicon-link"></span></a></li>*@
                        <li><a class="side-menu-item-content" href="@Url.Action("Index", "CoinManager")">Coin Notification<span class="sub_icon glyphicon glyphicon-link"></span></a></li>
                        <li><a class="side-menu-item-content" href="@Url.Action("Index", "Coin")">Coin Manager<span class="sub_icon glyphicon glyphicon-link"></span></a></li>
                        <li><a class="side-menu-item-content" href="@Url.Action("Index", "SettingBinance")">Binance Setting<span class="sub_icon glyphicon glyphicon-link"></span></a></li>
                    </ul>
                </div>

                <!-- Page content -->
                <div id="page-content-wrapper">
                    <!-- Keep all page content within the page-content inset div! -->
                    <div class="page-content inset">
                        @RenderBody()
                    </div>
                </div>

            </div>
        }
        else
        {
            @RenderBody()
        }

        <!-- Footer Layout -->
        @*@Html.Partial("_Footer.cshtml")*@
        <!-- End Footer Layout -->
        @{
            await Html.RenderPartialAsync("~/Areas/Web/Views/Shared/Asset/_BottomScript.cshtml").ConfigureAwait(true);
            await Html.RenderPartialAsync("~/Areas/Web/Views/Shared/Settings/Setup.cshtml").ConfigureAwait(true);
        }
        @RenderSection("Scripts", required: false)
    </div>
</body>
</html>

Bunny/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bunny</title>
    @{
        await Html.RenderPartialAsync("~/Areas/Web/Views/Shared/Asset/_Style.cshtml").ConfigureAwait(true);
    }
    <!-- JS -->
    <!-- jquery js -->
    <script type="text/javascript" src="~/lib/jquery/dist/jquery.js"></script>
    <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script type="text/javascript" src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>


    <!-- bootstrap js -->
    <script type="text/javascript" src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script type="text/javascript" src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>

    <!-- CSS Style -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="stylesheet" href="~/Assets/Style/Global.css" />

    <link rel="stylesheet" href="~/css/skins/Coin-skin.css" />

    <!-- global js -->
    <script src="~/js/Bunny.js"></script>
</head>
<body>
    @RenderBody()
    @RenderSection("Scripts", required: false)

   @{
           await Html.RenderPartialAsync("~/Areas/Web/Views/Shared/Asset/_BottomScript.cshtml").ConfigureAwait(true);
        await Html.RenderPartialAsync("~/Areas/Web/Views/Shared/Settings/Setup.cshtml").ConfigureAwait(true);
   }
</body>
</html>