Bunny/Areas/Web/Controllers/DashBoardController.cs
using Bunny.Areas.Web.Controllers.BaseController;
using Bunny.Middle.User;
using Microsoft.AspNetCore.Mvc;

namespace Bunny.Areas.Web.Controllers
{
    [Route(EndPoint)]
    public class DashBoardController : BaseWebController
    {
        public const string EndPoint = AreaName + "/dash-board";
        public const string DashBoardEndpoint = "";


        [Route(DashBoardEndpoint)]
        [HttpGet]
        public IActionResult Index()
        {
            var x = LoggedInUser.Current;
            return
            View();
        }
    }
}

Bunny/Areas/Web/Controllers/UserController.cs
using System.Threading.Tasks;
using Bunny.Areas.Web.Controllers.BaseController;
using Bunny.DataTable;
using Bunny.DataTable.Models.Request;
using Bunny.Extensions;
using Bunny.Middle;
using Bunny.Middle.Auth.Attributes;
using Bunny.Middle.User;
using Bunny.Model.User;
using Bunny.Service.Interface.User;
using Microsoft.AspNetCore.Mvc;

namespace Bunny.Areas.Web.Controllers
{
    [Route(EndPoint)]
    public class UserController : BaseWebController
    {
        public const string EndPoint = AreaName + "/user";
        public const string UserEndpoint = "index";
        public const string ListingEndpoint = "";
        public const string EditEndpoint = "edit";
        public const string SubmitEditEndpoint = "submit-edit";
        public const string AddEndpoint = "add";
        public const string SubmitAddEndpoint = "submit-add";
        public const string RemoveEndpoint = "remove";
        private readonly IUserService _userService;

        public UserController(IUserService userService)
        {
            _userService = userService;
        }
        // GET
        [Route(UserEndpoint)]
        [HttpGet]
        [Auth(Enums.Role.Admin, Enums.Role.Manager)]
        public IActionResult Index()
        {
            return
            View();
        }
        /// <summary>
        ///     Edit 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Route(EditEndpoint)]
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var model = await _userService.GetEdit(id).ConfigureAwait(true);
            return View(model);
        }
        [Route(SubmitEditEndpoint)]
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<JsonResult> SubmitEdit([FromBody]UserEditModel model)
        {
            if (!ModelState.IsValid)
            {
                //this.SetNotify("Edit Fail", "Edit user fail, please try again", NotifyStatus.Error);
                return Json("Fail");
            }

            await _userService.SubmitEdit(model, LoggedInUser.Current.Id, Constants.UserManager.PasswordDefault)
                .ConfigureAwait(false);
            //this.SetNotify("Edit Success", "User has been updated successful", NotifyStatus.Success);
            return Json("Success");
        }

        /// <summary>
        ///     Add 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Route(AddEndpoint)]
        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var model = await _userService.GetAdd().ConfigureAwait(true);
            return View(model);
        }
        [Route(SubmitAddEndpoint)]
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> SubmitAdd([FromForm]UserAddModel model)
        {
            if (!ModelState.IsValid)
            {
                this.SetNotify("Edit Fail", "Edit user fail, please try again", NotifyStatus.Error);
                return RedirectToAction("Add");
            }

            await _userService.SubmitAdd(model, LoggedInUser.Current.Id).ConfigureAwait(false);
            this.SetNotify("Edit Success", "User has been updated successful", NotifyStatus.Success);
            return RedirectToAction("Index");
        }

        [Route(RemoveEndpoint)]
        [HttpPost]
       
        public async Task<JsonResult> Remove(int id)
        {
            await _userService.RemoveAsync(id, LoggedInUser.Current.Id).ConfigureAwait(false);
            return Json(new { });
        }
    }
}

Bunny/Controllers/Components/HeaderViewComponent.cs
using System.Threading.Tasks;
using Bunny.Middle;
using Bunny.Middle.Auth.Filters;
using Bunny.Middle.User;
using Bunny.Model.User;
using Microsoft.AspNetCore.Mvc;

namespace Bunny.Controllers.Components
{
    [ServiceFilter(typeof(LoggedInUserBinderFilter))]
    public class HeaderViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(bool isAdminPortal)
        {
            var loggedInUserModel = LoggedInUser.Current;
            var isManager = loggedInUserModel.RoleId == (int)Enums.Role.Admin || loggedInUserModel.RoleId == (int)Enums.Role.Manager;
            var result = new UserHeaderViewModel
            {
                FirstName = loggedInUserModel?.FirstName,
                LastName = loggedInUserModel?.LastName,
                Id = loggedInUserModel?.Id ?? 0,
                IsAdminPortal = isAdminPortal,
                IsManager = isManager
            };
            return await Task.FromResult<IViewComponentResult>(View("Header", result)).ConfigureAwait(false);
        }
    }
}

Bunny/Controllers/Components/SidebarViewComponent.cs
using System.Threading.Tasks;
using Bunny.Middle.Auth.Filters;
using Bunny.Middle.User;
using Bunny.Model.User;
using Microsoft.AspNetCore.Mvc;

namespace Bunny.Controllers.Components
{
    public class SidebarViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.FromResult<IViewComponentResult>(View("Sidebar")).ConfigureAwait(false);
        }
    }
}

Bunny/Views/Shared/Components/Header/Header.cshtml
@model Bunny.Model.User.UserHeaderViewModel
@{
    var fullName = Model.LastName + " " + Model.FirstName;
    var currentUserId = Model.Id;
    var isAdminBoard = Model.IsAdminPortal;
    var isManager = Model.IsManager;
}
<script type="text/javascript">
    const urlHeader = {
        logout: '@Url.Action("Logout", "MasterPage")',
        home: '@Url.Action("Index", "MasterPage")'
    }
    var configsHeader = {
        urls: {
            logout: urlHeader.logout,
            home: urlHeader.home,
        },
        logoutBtn: "#btn-logout",
    };
    function initHeader() {
        $(configsHeader.logoutBtn).on('click', function() {
            console.log("logout userid = ", $("#current-user-id").text());
            $.ajax({
                url: configsHeader.urls.logout + "/?id=" + JSON.parse(`"${$("#current-user-id").text()}"`),
                type: 'Get',
                success: function (result) {
                    window.location.href = configsHeader.urls.home;
                },
                error: function (result) {
                    console.log("error", result);
                }
            });
        });
    }
    $(document).ready(function () {
        initHeader();
    });
</script>
<div class="page-header">
    <div class="hidden" id="current-user-id">@currentUserId</div>
    <div class="menu">
        <div class="container-fluid">
            <div class="navbar-header">
                @*<a href="#">Bootsnipp</a>*@
            </div>
            @*<div>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="#" ><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                        <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                    </ul>
                </div>*@
            <div style="height: 100%">
                <div class="dropdown-toggle user-information" data-toggle="dropdown">
                    <span>
                        <img alt="Avatar" title="Avatar" class="avatar user-avatar-container" src="~/images/global/user.png">
                    </span>
                    @*<span>@Model</span>*@
                    <span>@fullName</span>
                    @*<div class="user-name"></div>*@
                    @*<span class="caret"></span>*@
                </div>
                <ul class="dropdown-menu dropdown-menu-right">
                    @if (@isAdminBoard)
                    {
                        <li><a href="@Url.Action("Index", "DashBoard")">
                            <div><span>Dashboard</span></div></a></li>
                    }
                    else if (@isManager)
                    {
                        <li><a href="@Url.Action("Index", "User")">
                            <div><span>Admin Board</span></div></a></li>
                    }
                    <li>
                        <a href="@Url.Action("Logout", "MasterPage")">
                            <div><span>Logout</span></div>
                        </a>
                    </li>
                </ul>

            </div>
        </div>
    </div>

</div>